version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6379:6379'
  typescript-express-app:
      build:
        context: .
        dockerfile: Dockerfile
      links:
        - db
      ports: 
        - 5000:5000
      volumes:
        - ./src:/usr/app/src
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_DB=pilotr
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  redis:
  db: